apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
  labels: 
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: kaizen
    fsType: ext4